#!/bin/sh

ADDON_NAME=fbcheckinternet
RC_DIR=/usr/local/etc/config/rc.d
WWW_DIR=/usr/local/etc/config/addons/www/${ADDON_NAME}
ADDON_DIR=/usr/local/addons/${ADDON_NAME}
SWITCH_FILE=/etc/config/fbReplaceCheckInternet
CCU_MODEL=`grep VERSION /boot/VERSION | awk -F'[=.]' {'print $2'}`

replaceCheckInternet() {
	# Replace /bin/checkInternet with our script
	if [ ! -e /bin/checkInternet.orig ] && [ ! -L /bin/checkInternet ]; then
		logger -t ${ADDON_NAME} -p user.info "Replacing /bin/checkInternet with symlink to ${ADDON_DIR}/bin/fbcheckinternet.tcl"
		mount -o remount,rw /
		mv /bin/checkInternet /bin/checkInternet.orig
		ln -s ${ADDON_DIR}/bin/fbcheckinternet.tcl /bin/checkInternet
		sync
		mount -o remount,ro /
	fi
	if [ -f /var/status/hasInternetFritzBox ]; then
		rm -f /var/status/hasInternetFritzBox
	fi
}

restoreCheckInternet() {
	# Restore original /bin/checkInternet
	if [ -L /bin/checkInternet ] && [ -e /bin/checkInternet.orig ]; then
		logger -t ${ADDON_NAME} -p user.info "Restoring /bin/checkInternet"
		mount -o remount,rw /
		rm -f /bin/checkInternet
		mv /bin/checkInternet.orig /bin/checkInternet
		sync
		mount -o remount,ro /
	fi
}

createCronJob() {
	# Create cron job
	if ! /usr/bin/crontab -l | grep -q "${ADDON_DIR}/bin/fbcheckinternet.tcl" 2>/dev/null; then
		TMPCRON=`mktemp`
		/usr/bin/crontab -l > ${TMPCRON}
		echo "*/3 * * * * ${ADDON_DIR}/bin/fbcheckinternet.tcl" >> ${TMPCRON}
		/usr/bin/crontab ${TMPCRON}
		rm -f ${TMPCRON}
	fi
}

removeCronJob() {
	# Remove cron job
	if /usr/bin/crontab -l | grep -q "${ADDON_DIR}/bin/fbcheckinternet.tcl" 2>/dev/null; then
		TMPCRON=`mktemp`
		SED=`mktemp`
		echo ${ADDON_DIR}/bin/fbcheckinternet.tcl | sed -e 's/\//\\\//g' > ${SED}
		/usr/bin/crontab -l | sed "/`cat ${SED}`/d" > ${TMPCRON}
		/usr/bin/crontab ${TMPCRON}
		rm -f ${TMPCRON}
		rm -f ${SED}
	fi
}

case "$1" in
	""|init|start|restart)
		if [ -f ${SWITCH_FILE} ]; then
			# Replace /bin/checkInternet
			replaceCheckInternet
			if [ ${CCU_MODEL} -eq 2 ]; then
				# on CCU2 Cron Job is always required
				createCronJob
			else
				# remove cron job on CCU3 and RaspberryMatic
				removeCronJob
			fi
		else
			# Restore /bin/checkInternet
			restoreCheckInternet
			# create Cron Job to update Sysvar periodically
			createCronJob
		fi

		# Execute current checkInternet to update the Status in the System
		/bin/checkInternet

		exit 0
	;;
	stop)
		exit 0
	;;
	info)
		echo "Info: <b>FRITZ!Box Internet Check Addon</b><br />"
		echo "Version: $(cat ${ADDON_DIR}/VERSION)"
		echo "Name: FRITZ!Box Internet Check"
		echo "Operations: uninstall restart"
		echo "Update: /addons/${ADDON_NAME}/update-check.cgi"
	;;
	uninstall)
		# Restore original /bin/checkInternet
		restoreCheckInternet

		# Remove cron job
		removeCronJob

		# Remove Addon Files
		rm -rf ${ADDON_DIR}
		rm -rf ${WWW_DIR}
		rm -f ${RC_DIR}/${ADDON_NAME}

		# Remove State File, if exists
		if [ -f /var/status/hasInternetFritzBox ]; then
			rm -f /var/status/hasInternetFritzBox
		fi

		# Remove monit config, if exists
		if [ -e /usr/local/etc/monit_fbcheckinternet.cfg ]; then
			rm -f /usr/local/etc/monit_fbcheckinternet.cfg
			if [ -x /usr/bin/monit ]; then
				/usr/bin/monit reload
			fi
		fi

		# Execute current checkInternet to update the Status in the System
		/bin/checkInternet

		exit 0
	;;
	*)
		echo "Usage: $ADDON_NAME {start|stop|restart|info|uninstall}" >&2
		exit 1
	;;
esac
