#!/bin/sh

ADDON_NAME=fbcheckinternet
RC_DIR=/usr/local/etc/config/rc.d
WWW_DIR=/usr/local/etc/config/addons/www/${ADDON_NAME}
ADDON_DIR=/usr/local/addons/${ADDON_NAME}

mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
	mount /usr/local
fi

#Copy Files
mkdir -p ${ADDON_DIR}
mkdir -p ${WWW_DIR}
cp -af bin ${ADDON_DIR}
chmod 755 ${ADDON_DIR}/bin/*
cp -f VERSION ${ADDON_DIR}
cp -f rc.d/${ADDON_NAME} ${RC_DIR}
chmod +x ${RC_DIR}/${ADDON_NAME}
cp -f www/update-check.cgi ${WWW_DIR}
chmod 755 ${WWW_DIR}/*

#Copy monit config only if monit exists
if [ -x /usr/bin/monit ]; then
	cp -f etc/monit_fbcheckinternet.cfg /usr/local/etc/
	/usr/bin/monit reload
fi

${RC_DIR}/${ADDON_NAME} init

sync
exit 0
